apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-role
  namespace: default
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "namespaces", "services"]
    verbs: ["get", "watch", "list"]
