apiVersion: apps/v1
kind: Deployment
metadata:
 name: elasticsearch-deployment
spec:
 selector:
  matchLabels:
   component: elasticsearch
 template:
  metadata:
   labels:
    component: elasticsearch
  spec:
   containers:
   - name: elasticsearch
     image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
     env:
      - name: discovery.type
        value: single-node
     ports:
     - containerPort: 9200
       name: http
       protocol: TCP
     resources:
      limits:
       cpu: 1500m
       memory: "1024Mi"
      requests:
       cpu: 500m
       memory: "256Mi"
