apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
   matchLabels:
    run: kibana
  template:
   metadata:
    labels:
     run: kibana
   spec:
    containers:
    - name: kibana
      image: docker.elastic.co/kibana/kibana:7.4.1
      env:
      - name: ELASTICSEARCH_URL
        value: https://108.61.135.86:31015
      - name: XPACK_SECURITY_ENABLED
        value: "true"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
