apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
    component: kibana
    app.kubernetes.io/name: kibana-service
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:8.7.0
        env:
        - name: "setup.dashboards.enabled"
          value: "true"
        - name: ELASTICSEARCH_HOSTS
          value: "http://108.61.135.86:30146"
        - name: ELASTICSEARCH_USERNAME
          value: kibana_system
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: db-secret-elastic
        - name: xpack.reporting.encryptionKey
          value: "ENCRIPTIONKEY"
        - name: xpack.reporting.enabled
          value: "true"
        imagePullPolicy: IfNotPresent
        name: kibana
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
