apiVersion: v1
kind: Pod
metadata:
 name: my-resource-pod
spec:
 containers:
 - name: my-app-resource-container
   image: busybox
   command: ['sh', '-c', 'echo Hello Kubernetes resource requirement POD && sleep 3600']
   resources:
    requests:
     memory: "64Mi"
     cpu: "250m"
    limits:
     memory: "128Mi"
     cpu: "500m"
