/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorldFile */

#ifndef _Included_HelloWorldFile
#define _Included_HelloWorldFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorldFile
 * Method:    print
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HelloWorldFile_print
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
