apiVersion: v1
kind: Pod
metadata:
 name: my-service-account-pod
spec:
 serviceAccountName: my-service-account  
 containers:
 - name: myapp-service-account-container
   image: busybox
   command: ['sh', '-c', "echo HELLO WORLD FROM my service account container && sleep 3600"]

